apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block
  namespace: openshift-local-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: In
            values:
              - ""
  storageClassName: localblock
  volumeMode: Block
  maxDeviceCount: {{ .Values.lso.devicecount }}
  deviceInclusionSpec:
    deviceTypes:
    - disk
    deviceMechanicalProperties:
    - {{ .Values.lso.type }}
    minSize: {{ .Values.lso.minSize }}
    maxSize: {{ .Values.lso.maxSize }}
