apiVersion: batch/v1
kind: Job
metadata:
  name: enable-odf-plugin
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    compare-options: IgnoreExtraneous
  namespace: openshift-data-foundation
spec:
  template:
    spec:
      containers:
      - name: enable-odf-plugin
        command:
            - /bin/bash
            - -c
            - |
              echo "Patching the storaclass to make it default SC"
              oc patch storageclass ocs-storagecluster-ceph-rbd --patch '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}' --type merge
              if [ $? = 0 ]
              then
                  echo "Patching SC succeeded"
              else
                  echo "Failed to patch storageclass"
              fi
        image: registry.redhat.io/openshift4/ose-cli:v4.11
      serviceAccount: patch-odf-sc
      serviceAccountName: patch-odf-sc
      restartPolicy: Never
